version: '3.9'

services:
  rag-telegram-bot:
    build: .
    container_name: rag-telegram-bot
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./db:/app/db
    restart: unless-stopped
