apiVersion: v1
kind: Service
metadata:
  name: rag-telegram-bot-service
spec:
  selector:
    app: rag-telegram-bot
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
